version: 0.2.0.1
github: tek/exon
license: BSD-2-Clause-Patent
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "haskell@tryp.io"
copyright: "2021 Torsten Schmits"
category: String
build-type: Simple
