name: lower-init
on: workflow_dispatch
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  lower-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: DeterminateSystems/nix-installer-action@v21
      with:
        extra-conf: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v16
      with:
        name: tek
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - id: bounds
      run: nix run .#lower.init -- --output=ga-pr --build-timeout=3600
    - name: pr
      if: steps.bounds.outputs.commit-message
      uses: peter-evans/create-pull-request@v7
      with: ${{ steps.bounds.outputs }}
