name: lower-optimize
on: workflow_dispatch
permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  lower-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: cachix/cachix-action@v14
      with:
        name: tek
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}
    - id: bounds
      run: nix run .#lower.optimize -- --output=ga-pr --build-timeout=3600
    - name: pr
      if: steps.bounds.outputs.commit-message
      uses: peter-evans/create-pull-request@v5
      with: ${{ steps.bounds.outputs }}
